//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIPipelines) DeepCopyInto(out *AIPipelines) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIPipelines.
func (in *AIPipelines) DeepCopy() *AIPipelines {
	if in == nil {
		return nil
	}
	out := new(AIPipelines)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIPipelines) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIPipelinesList) DeepCopyInto(out *AIPipelinesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIPipelines, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIPipelinesList.
func (in *AIPipelinesList) DeepCopy() *AIPipelinesList {
	if in == nil {
		return nil
	}
	out := new(AIPipelinesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIPipelinesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIPipelinesSpec) DeepCopyInto(out *AIPipelinesSpec) {
	*out = *in
	if in.ArgoWorkflowsControllers != nil {
		in, out := &in.ArgoWorkflowsControllers, &out.ArgoWorkflowsControllers
		*out = new(ArgoWorkflowsControllersSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIPipelinesSpec.
func (in *AIPipelinesSpec) DeepCopy() *AIPipelinesSpec {
	if in == nil {
		return nil
	}
	out := new(AIPipelinesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIPipelinesStatus) DeepCopyInto(out *AIPipelinesStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.ComponentReleaseStatus.DeepCopyInto(&out.ComponentReleaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIPipelinesStatus.
func (in *AIPipelinesStatus) DeepCopy() *AIPipelinesStatus {
	if in == nil {
		return nil
	}
	out := new(AIPipelinesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoWorkflowsControllersSpec) DeepCopyInto(out *ArgoWorkflowsControllersSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoWorkflowsControllersSpec.
func (in *ArgoWorkflowsControllersSpec) DeepCopy() *ArgoWorkflowsControllersSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoWorkflowsControllersSpec)
	in.DeepCopyInto(out)
	return out
}
