apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- applications
- ../../../argo/crds
namespace: redhat-ods-applications

patches:
- patch: |-
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: data-science-pipelines-operator-service-monitor
    $patch: delete
  target:
    group: monitoring.coreos.com
    version: v1
    kind: ServiceMonitor
    name: data-science-pipelines-operator-service-monitor
