apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../openshift
- ../../argo
namespace: opendatahub

replacements:
- source:
    kind: ConfigMap
    name: dspo-parameters
    fieldPath: metadata.namespace
  targets:
  - select:
      kind: PrometheusRule
      name: datasciencepipelines-prometheusrules
    fieldPaths:
    - spec.groups.*.rules.*.labels.namespace
