apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    # Points to the component repo where the PR is opened
    build.appstudio.openshift.io/repo: https://github.com/opendatahub-io/data-science-pipelines-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[issue_comment]"
    pipelinesascode.tekton.dev/on-comment: "^/test-early-gate"
  labels:
    appstudio.openshift.io/application: opendatahub-builds
    appstudio.openshift.io/component: early-gate-test
    pipelines.appstudio.openshift.io/type: build
  name: early-gate-test-on-comment
  namespace: open-data-hub-tenant
spec:
  params:
  - name: group-components
    value: '{ "odh-data-science-pipelines-operator-controller-ci": "opendatahub/data-science-pipelines-operator" }'
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/opendatahub-io/odh-konflux-central.git
    - name: revision
      value: 'earlygate'
    - name: pathInRepo
      value: e2e-early-gate/early-gate-component-pipeline.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-odh-data-science-pipelines-operator-controller
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
  - name: netrc
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
