apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/opendatahub-io/data-science-pipelines-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "stable"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: opendatahub-release
    appstudio.openshift.io/component: odh-data-science-pipelines-operator-controller
    pipelines.appstudio.openshift.io/type: build
  name: odh-data-science-pipelines-operator-controller-on-pull-request
  namespace: open-data-hub-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/opendatahub/data-science-pipelines-operator:{{revision}}
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: .
  - name: additional-tags
    value:
    - '{{target_branch}}-{{revision}}'
    - 'odh-stable'
  - name: pipeline-type
    value: pull-request
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/opendatahub-io/odh-konflux-central.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipeline/multi-arch-container-build.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-odh-data-science-pipelines-operator-controller
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
