name: Trigger build images for PRs
on:
  pull_request:
    paths:
      - .github/workflows/build-prs-trigger.yaml
      - go.mod
      - go.sum
      - controllers/**
      - api/**
      - config/**
    types:
      - opened
      - reopened
      - closed
      - synchronize
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  upload-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Save PR payload
        shell: bash
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_STATE: ${{ github.event.pull_request.state }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          EVENT_ACTION: ${{ github.event.action }}
        run: |
          mkdir -p ./pr
          echo "$PR_NUMBER" >> ./pr/pr_number
          echo "$PR_STATE" >> ./pr/pr_state
          echo "$HEAD_SHA" >> ./pr/head_sha
          echo "$EVENT_ACTION" >> ./pr/event_action
      - uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/
