name: Nightly Testing
on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * *
jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run Build
        run: make build
      - name: Run Unit Tests
        run: make unittest
      - name: Run Functional Tests
        run: make functest
      # TODO: implement some sort of notification mechanism
